/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as PupilsRouteImport } from './routes/pupils'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PupilsIndexRouteImport } from './routes/pupils.index'
import { Route as PupilsNewRouteImport } from './routes/pupils.new'
import { Route as PupilsIdRouteImport } from './routes/pupils.$id'
import { Route as MessagesIdRouteImport } from './routes/messages.$id'
import { Route as LessonsNewRouteImport } from './routes/lessons.new'
import { Route as LessonsIdRouteImport } from './routes/lessons.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const PupilsRoute = PupilsRouteImport.update({
  id: '/pupils',
  path: '/pupils',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PupilsIndexRoute = PupilsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PupilsRoute,
} as any)
const PupilsNewRoute = PupilsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PupilsRoute,
} as any)
const PupilsIdRoute = PupilsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PupilsRoute,
} as any)
const MessagesIdRoute = MessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MessagesRoute,
} as any)
const LessonsNewRoute = LessonsNewRouteImport.update({
  id: '/lessons/new',
  path: '/lessons/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIdRoute = LessonsIdRouteImport.update({
  id: '/lessons/$id',
  path: '/lessons/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/earnings': typeof EarningsRoute
  '/expenses': typeof ExpensesRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/pupils': typeof PupilsRouteWithChildren
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/lessons/$id': typeof LessonsIdRoute
  '/lessons/new': typeof LessonsNewRoute
  '/messages/$id': typeof MessagesIdRoute
  '/pupils/$id': typeof PupilsIdRoute
  '/pupils/new': typeof PupilsNewRoute
  '/pupils/': typeof PupilsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/earnings': typeof EarningsRoute
  '/expenses': typeof ExpensesRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/lessons/$id': typeof LessonsIdRoute
  '/lessons/new': typeof LessonsNewRoute
  '/messages/$id': typeof MessagesIdRoute
  '/pupils/$id': typeof PupilsIdRoute
  '/pupils/new': typeof PupilsNewRoute
  '/pupils': typeof PupilsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/earnings': typeof EarningsRoute
  '/expenses': typeof ExpensesRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/pupils': typeof PupilsRouteWithChildren
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/lessons/$id': typeof LessonsIdRoute
  '/lessons/new': typeof LessonsNewRoute
  '/messages/$id': typeof MessagesIdRoute
  '/pupils/$id': typeof PupilsIdRoute
  '/pupils/new': typeof PupilsNewRoute
  '/pupils/': typeof PupilsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/earnings'
    | '/expenses'
    | '/home'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/payments'
    | '/pupils'
    | '/schedule'
    | '/settings'
    | '/lessons/$id'
    | '/lessons/new'
    | '/messages/$id'
    | '/pupils/$id'
    | '/pupils/new'
    | '/pupils/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/earnings'
    | '/expenses'
    | '/home'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/payments'
    | '/schedule'
    | '/settings'
    | '/lessons/$id'
    | '/lessons/new'
    | '/messages/$id'
    | '/pupils/$id'
    | '/pupils/new'
    | '/pupils'
  id:
    | '__root__'
    | '/'
    | '/earnings'
    | '/expenses'
    | '/home'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/payments'
    | '/pupils'
    | '/schedule'
    | '/settings'
    | '/lessons/$id'
    | '/lessons/new'
    | '/messages/$id'
    | '/pupils/$id'
    | '/pupils/new'
    | '/pupils/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EarningsRoute: typeof EarningsRoute
  ExpensesRoute: typeof ExpensesRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  PaymentsRoute: typeof PaymentsRoute
  PupilsRoute: typeof PupilsRouteWithChildren
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  LessonsIdRoute: typeof LessonsIdRoute
  LessonsNewRoute: typeof LessonsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pupils': {
      id: '/pupils'
      path: '/pupils'
      fullPath: '/pupils'
      preLoaderRoute: typeof PupilsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pupils/': {
      id: '/pupils/'
      path: '/'
      fullPath: '/pupils/'
      preLoaderRoute: typeof PupilsIndexRouteImport
      parentRoute: typeof PupilsRoute
    }
    '/pupils/new': {
      id: '/pupils/new'
      path: '/new'
      fullPath: '/pupils/new'
      preLoaderRoute: typeof PupilsNewRouteImport
      parentRoute: typeof PupilsRoute
    }
    '/pupils/$id': {
      id: '/pupils/$id'
      path: '/$id'
      fullPath: '/pupils/$id'
      preLoaderRoute: typeof PupilsIdRouteImport
      parentRoute: typeof PupilsRoute
    }
    '/messages/$id': {
      id: '/messages/$id'
      path: '/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof MessagesIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/lessons/new': {
      id: '/lessons/new'
      path: '/lessons/new'
      fullPath: '/lessons/new'
      preLoaderRoute: typeof LessonsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$id': {
      id: '/lessons/$id'
      path: '/lessons/$id'
      fullPath: '/lessons/$id'
      preLoaderRoute: typeof LessonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MessagesRouteChildren {
  MessagesIdRoute: typeof MessagesIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesIdRoute: MessagesIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

interface PupilsRouteChildren {
  PupilsIdRoute: typeof PupilsIdRoute
  PupilsNewRoute: typeof PupilsNewRoute
  PupilsIndexRoute: typeof PupilsIndexRoute
}

const PupilsRouteChildren: PupilsRouteChildren = {
  PupilsIdRoute: PupilsIdRoute,
  PupilsNewRoute: PupilsNewRoute,
  PupilsIndexRoute: PupilsIndexRoute,
}

const PupilsRouteWithChildren =
  PupilsRoute._addFileChildren(PupilsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EarningsRoute: EarningsRoute,
  ExpensesRoute: ExpensesRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  PaymentsRoute: PaymentsRoute,
  PupilsRoute: PupilsRouteWithChildren,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  LessonsIdRoute: LessonsIdRoute,
  LessonsNewRoute: LessonsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
