/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeeklyreportRouteImport } from './routes/weeklyreport'
import { Route as WaiversRouteImport } from './routes/waivers'
import { Route as WaitinglistRouteImport } from './routes/waitinglist'
import { Route as VehicleRouteImport } from './routes/vehicle'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as TestdayRouteImport } from './routes/testday'
import { Route as TaxRouteImport } from './routes/tax'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as StandardsRouteImport } from './routes/standards'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SatnavRouteImport } from './routes/satnav'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResetpasswordRouteImport } from './routes/resetpassword'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReminderRouteImport } from './routes/reminder'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as QuickavailabilityRouteImport } from './routes/quickavailability'
import { Route as QuickaccessRouteImport } from './routes/quickaccess'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as OutstandingRouteImport } from './routes/outstanding'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsettingsRouteImport } from './routes/notificationsettings'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as MtdRouteImport } from './routes/mtd'
import { Route as MonthendRouteImport } from './routes/monthend'
import { Route as MileageRouteImport } from './routes/mileage'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as ManifestRouteImport } from './routes/manifest'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as LivesessionRouteImport } from './routes/livesession'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HealthRouteImport } from './routes/health'
import { Route as GapsRouteImport } from './routes/gaps'
import { Route as FuelRouteImport } from './routes/fuel'
import { Route as ForgotpasswordRouteImport } from './routes/forgotpassword'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as EodRouteImport } from './routes/eod'
import { Route as EnquiriesRouteImport } from './routes/enquiries'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DiaryRouteImport } from './routes/diary'
import { Route as DataimportRouteImport } from './routes/dataimport'
import { Route as CpdRouteImport } from './routes/cpd'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as CalendarsyncRouteImport } from './routes/calendarsync'
import { Route as BulkmessageRouteImport } from './routes/bulkmessage'
import { Route as BriefingRouteImport } from './routes/briefing'
import { Route as AvailabilityRouteImport } from './routes/availability'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuotesIndexRouteImport } from './routes/quotes.index'
import { Route as PupilsIndexRouteImport } from './routes/pupils.index'
import { Route as NotesIndexRouteImport } from './routes/notes.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as QuotesNewRouteImport } from './routes/quotes.new'
import { Route as PupilsNewRouteImport } from './routes/pupils.new'
import { Route as PupilsIdRouteImport } from './routes/pupils.$id'
import { Route as NotesIdRouteImport } from './routes/notes.$id'
import { Route as MessagesIdRouteImport } from './routes/messages.$id'
import { Route as LessonsNewRouteImport } from './routes/lessons.new'
import { Route as LessonsIdRouteImport } from './routes/lessons.$id'
import { Route as CoursesNewRouteImport } from './routes/courses.new'
import { Route as CoursesIdRouteImport } from './routes/courses.$id'
import { Route as PupilsProgressIdRouteImport } from './routes/pupils.progress.$id'
import { Route as PupilsHistoryIdRouteImport } from './routes/pupils.history.$id'
import { Route as PupilsEditIdRouteImport } from './routes/pupils.edit.$id'
import { Route as LessonsRescheduleIdRouteImport } from './routes/lessons.reschedule.$id'
import { Route as LessonsFeedbackIdRouteImport } from './routes/lessons.feedback.$id'
import { Route as LessonsEditIdRouteImport } from './routes/lessons.edit.$id'

const WeeklyreportRoute = WeeklyreportRouteImport.update({
  id: '/weeklyreport',
  path: '/weeklyreport',
  getParentRoute: () => rootRouteImport,
} as any)
const WaiversRoute = WaiversRouteImport.update({
  id: '/waivers',
  path: '/waivers',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitinglistRoute = WaitinglistRouteImport.update({
  id: '/waitinglist',
  path: '/waitinglist',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleRoute = VehicleRouteImport.update({
  id: '/vehicle',
  path: '/vehicle',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const TestdayRoute = TestdayRouteImport.update({
  id: '/testday',
  path: '/testday',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxRoute = TaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsRoute = StandardsRouteImport.update({
  id: '/standards',
  path: '/standards',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SatnavRoute = SatnavRouteImport.update({
  id: '/satnav',
  path: '/satnav',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetpasswordRoute = ResetpasswordRouteImport.update({
  id: '/resetpassword',
  path: '/resetpassword',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReminderRoute = ReminderRouteImport.update({
  id: '/reminder',
  path: '/reminder',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickavailabilityRoute = QuickavailabilityRouteImport.update({
  id: '/quickavailability',
  path: '/quickavailability',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickaccessRoute = QuickaccessRouteImport.update({
  id: '/quickaccess',
  path: '/quickaccess',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const OutstandingRoute = OutstandingRouteImport.update({
  id: '/outstanding',
  path: '/outstanding',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsettingsRoute = NotificationsettingsRouteImport.update({
  id: '/notificationsettings',
  path: '/notificationsettings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const MtdRoute = MtdRouteImport.update({
  id: '/mtd',
  path: '/mtd',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthendRoute = MonthendRouteImport.update({
  id: '/monthend',
  path: '/monthend',
  getParentRoute: () => rootRouteImport,
} as any)
const MileageRoute = MileageRouteImport.update({
  id: '/mileage',
  path: '/mileage',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestRoute = ManifestRouteImport.update({
  id: '/manifest',
  path: '/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const LivesessionRoute = LivesessionRouteImport.update({
  id: '/livesession',
  path: '/livesession',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const GapsRoute = GapsRouteImport.update({
  id: '/gaps',
  path: '/gaps',
  getParentRoute: () => rootRouteImport,
} as any)
const FuelRoute = FuelRouteImport.update({
  id: '/fuel',
  path: '/fuel',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotpasswordRoute = ForgotpasswordRouteImport.update({
  id: '/forgotpassword',
  path: '/forgotpassword',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const EodRoute = EodRouteImport.update({
  id: '/eod',
  path: '/eod',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiriesRoute = EnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaryRoute = DiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => rootRouteImport,
} as any)
const DataimportRoute = DataimportRouteImport.update({
  id: '/dataimport',
  path: '/dataimport',
  getParentRoute: () => rootRouteImport,
} as any)
const CpdRoute = CpdRouteImport.update({
  id: '/cpd',
  path: '/cpd',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarsyncRoute = CalendarsyncRouteImport.update({
  id: '/calendarsync',
  path: '/calendarsync',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkmessageRoute = BulkmessageRouteImport.update({
  id: '/bulkmessage',
  path: '/bulkmessage',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingRoute = BriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityRoute = AvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesIndexRoute = QuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PupilsIndexRoute = PupilsIndexRouteImport.update({
  id: '/pupils/',
  path: '/pupils/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotesRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesNewRoute = QuotesNewRouteImport.update({
  id: '/quotes/new',
  path: '/quotes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PupilsNewRoute = PupilsNewRouteImport.update({
  id: '/pupils/new',
  path: '/pupils/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PupilsIdRoute = PupilsIdRouteImport.update({
  id: '/pupils/$id',
  path: '/pupils/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIdRoute = NotesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NotesRoute,
} as any)
const MessagesIdRoute = MessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MessagesRoute,
} as any)
const LessonsNewRoute = LessonsNewRouteImport.update({
  id: '/lessons/new',
  path: '/lessons/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIdRoute = LessonsIdRouteImport.update({
  id: '/lessons/$id',
  path: '/lessons/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesNewRoute = CoursesNewRouteImport.update({
  id: '/courses/new',
  path: '/courses/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIdRoute = CoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PupilsProgressIdRoute = PupilsProgressIdRouteImport.update({
  id: '/pupils/progress/$id',
  path: '/pupils/progress/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PupilsHistoryIdRoute = PupilsHistoryIdRouteImport.update({
  id: '/pupils/history/$id',
  path: '/pupils/history/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PupilsEditIdRoute = PupilsEditIdRouteImport.update({
  id: '/pupils/edit/$id',
  path: '/pupils/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRescheduleIdRoute = LessonsRescheduleIdRouteImport.update({
  id: '/lessons/reschedule/$id',
  path: '/lessons/reschedule/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsFeedbackIdRoute = LessonsFeedbackIdRouteImport.update({
  id: '/lessons/feedback/$id',
  path: '/lessons/feedback/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsEditIdRoute = LessonsEditIdRouteImport.update({
  id: '/lessons/edit/$id',
  path: '/lessons/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRoute
  '/availability': typeof AvailabilityRoute
  '/briefing': typeof BriefingRoute
  '/bulkmessage': typeof BulkmessageRoute
  '/calendarsync': typeof CalendarsyncRoute
  '/certifications': typeof CertificationsRoute
  '/checklist': typeof ChecklistRoute
  '/cpd': typeof CpdRoute
  '/dataimport': typeof DataimportRoute
  '/diary': typeof DiaryRoute
  '/documents': typeof DocumentsRoute
  '/earnings': typeof EarningsRoute
  '/enquiries': typeof EnquiriesRoute
  '/eod': typeof EodRoute
  '/expenses': typeof ExpensesRoute
  '/forgotpassword': typeof ForgotpasswordRoute
  '/fuel': typeof FuelRoute
  '/gaps': typeof GapsRoute
  '/health': typeof HealthRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/livesession': typeof LivesessionRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/manifest': typeof ManifestRoute
  '/messages': typeof MessagesRouteWithChildren
  '/mileage': typeof MileageRoute
  '/monthend': typeof MonthendRoute
  '/mtd': typeof MtdRoute
  '/notes': typeof NotesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/notificationsettings': typeof NotificationsettingsRoute
  '/onboarding': typeof OnboardingRoute
  '/outstanding': typeof OutstandingRoute
  '/payments': typeof PaymentsRoute
  '/performance': typeof PerformanceRoute
  '/pipeline': typeof PipelineRoute
  '/profile': typeof ProfileRoute
  '/quickaccess': typeof QuickaccessRoute
  '/quickavailability': typeof QuickavailabilityRoute
  '/referrals': typeof ReferralsRoute
  '/register': typeof RegisterRoute
  '/reminder': typeof ReminderRoute
  '/reports': typeof ReportsRoute
  '/resetpassword': typeof ResetpasswordRoute
  '/resources': typeof ResourcesRoute
  '/reviews': typeof ReviewsRoute
  '/rewards': typeof RewardsRoute
  '/satnav': typeof SatnavRoute
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/standards': typeof StandardsRoute
  '/subscription': typeof SubscriptionRoute
  '/tax': typeof TaxRoute
  '/testday': typeof TestdayRoute
  '/tests': typeof TestsRoute
  '/todos': typeof TodosRoute
  '/vehicle': typeof VehicleRoute
  '/waitinglist': typeof WaitinglistRoute
  '/waivers': typeof WaiversRoute
  '/weeklyreport': typeof WeeklyreportRoute
  '/courses/$id': typeof CoursesIdRoute
  '/courses/new': typeof CoursesNewRoute
  '/lessons/$id': typeof LessonsIdRoute
  '/lessons/new': typeof LessonsNewRoute
  '/messages/$id': typeof MessagesIdRoute
  '/notes/$id': typeof NotesIdRoute
  '/pupils/$id': typeof PupilsIdRoute
  '/pupils/new': typeof PupilsNewRoute
  '/quotes/new': typeof QuotesNewRoute
  '/courses/': typeof CoursesIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/pupils/': typeof PupilsIndexRoute
  '/quotes/': typeof QuotesIndexRoute
  '/lessons/edit/$id': typeof LessonsEditIdRoute
  '/lessons/feedback/$id': typeof LessonsFeedbackIdRoute
  '/lessons/reschedule/$id': typeof LessonsRescheduleIdRoute
  '/pupils/edit/$id': typeof PupilsEditIdRoute
  '/pupils/history/$id': typeof PupilsHistoryIdRoute
  '/pupils/progress/$id': typeof PupilsProgressIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRoute
  '/availability': typeof AvailabilityRoute
  '/briefing': typeof BriefingRoute
  '/bulkmessage': typeof BulkmessageRoute
  '/calendarsync': typeof CalendarsyncRoute
  '/certifications': typeof CertificationsRoute
  '/checklist': typeof ChecklistRoute
  '/cpd': typeof CpdRoute
  '/dataimport': typeof DataimportRoute
  '/diary': typeof DiaryRoute
  '/documents': typeof DocumentsRoute
  '/earnings': typeof EarningsRoute
  '/enquiries': typeof EnquiriesRoute
  '/eod': typeof EodRoute
  '/expenses': typeof ExpensesRoute
  '/forgotpassword': typeof ForgotpasswordRoute
  '/fuel': typeof FuelRoute
  '/gaps': typeof GapsRoute
  '/health': typeof HealthRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/livesession': typeof LivesessionRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/manifest': typeof ManifestRoute
  '/messages': typeof MessagesRouteWithChildren
  '/mileage': typeof MileageRoute
  '/monthend': typeof MonthendRoute
  '/mtd': typeof MtdRoute
  '/notifications': typeof NotificationsRoute
  '/notificationsettings': typeof NotificationsettingsRoute
  '/onboarding': typeof OnboardingRoute
  '/outstanding': typeof OutstandingRoute
  '/payments': typeof PaymentsRoute
  '/performance': typeof PerformanceRoute
  '/pipeline': typeof PipelineRoute
  '/profile': typeof ProfileRoute
  '/quickaccess': typeof QuickaccessRoute
  '/quickavailability': typeof QuickavailabilityRoute
  '/referrals': typeof ReferralsRoute
  '/register': typeof RegisterRoute
  '/reminder': typeof ReminderRoute
  '/reports': typeof ReportsRoute
  '/resetpassword': typeof ResetpasswordRoute
  '/resources': typeof ResourcesRoute
  '/reviews': typeof ReviewsRoute
  '/rewards': typeof RewardsRoute
  '/satnav': typeof SatnavRoute
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/standards': typeof StandardsRoute
  '/subscription': typeof SubscriptionRoute
  '/tax': typeof TaxRoute
  '/testday': typeof TestdayRoute
  '/tests': typeof TestsRoute
  '/todos': typeof TodosRoute
  '/vehicle': typeof VehicleRoute
  '/waitinglist': typeof WaitinglistRoute
  '/waivers': typeof WaiversRoute
  '/weeklyreport': typeof WeeklyreportRoute
  '/courses/$id': typeof CoursesIdRoute
  '/courses/new': typeof CoursesNewRoute
  '/lessons/$id': typeof LessonsIdRoute
  '/lessons/new': typeof LessonsNewRoute
  '/messages/$id': typeof MessagesIdRoute
  '/notes/$id': typeof NotesIdRoute
  '/pupils/$id': typeof PupilsIdRoute
  '/pupils/new': typeof PupilsNewRoute
  '/quotes/new': typeof QuotesNewRoute
  '/courses': typeof CoursesIndexRoute
  '/notes': typeof NotesIndexRoute
  '/pupils': typeof PupilsIndexRoute
  '/quotes': typeof QuotesIndexRoute
  '/lessons/edit/$id': typeof LessonsEditIdRoute
  '/lessons/feedback/$id': typeof LessonsFeedbackIdRoute
  '/lessons/reschedule/$id': typeof LessonsRescheduleIdRoute
  '/pupils/edit/$id': typeof PupilsEditIdRoute
  '/pupils/history/$id': typeof PupilsHistoryIdRoute
  '/pupils/progress/$id': typeof PupilsProgressIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRoute
  '/availability': typeof AvailabilityRoute
  '/briefing': typeof BriefingRoute
  '/bulkmessage': typeof BulkmessageRoute
  '/calendarsync': typeof CalendarsyncRoute
  '/certifications': typeof CertificationsRoute
  '/checklist': typeof ChecklistRoute
  '/cpd': typeof CpdRoute
  '/dataimport': typeof DataimportRoute
  '/diary': typeof DiaryRoute
  '/documents': typeof DocumentsRoute
  '/earnings': typeof EarningsRoute
  '/enquiries': typeof EnquiriesRoute
  '/eod': typeof EodRoute
  '/expenses': typeof ExpensesRoute
  '/forgotpassword': typeof ForgotpasswordRoute
  '/fuel': typeof FuelRoute
  '/gaps': typeof GapsRoute
  '/health': typeof HealthRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/livesession': typeof LivesessionRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/manifest': typeof ManifestRoute
  '/messages': typeof MessagesRouteWithChildren
  '/mileage': typeof MileageRoute
  '/monthend': typeof MonthendRoute
  '/mtd': typeof MtdRoute
  '/notes': typeof NotesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/notificationsettings': typeof NotificationsettingsRoute
  '/onboarding': typeof OnboardingRoute
  '/outstanding': typeof OutstandingRoute
  '/payments': typeof PaymentsRoute
  '/performance': typeof PerformanceRoute
  '/pipeline': typeof PipelineRoute
  '/profile': typeof ProfileRoute
  '/quickaccess': typeof QuickaccessRoute
  '/quickavailability': typeof QuickavailabilityRoute
  '/referrals': typeof ReferralsRoute
  '/register': typeof RegisterRoute
  '/reminder': typeof ReminderRoute
  '/reports': typeof ReportsRoute
  '/resetpassword': typeof ResetpasswordRoute
  '/resources': typeof ResourcesRoute
  '/reviews': typeof ReviewsRoute
  '/rewards': typeof RewardsRoute
  '/satnav': typeof SatnavRoute
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/standards': typeof StandardsRoute
  '/subscription': typeof SubscriptionRoute
  '/tax': typeof TaxRoute
  '/testday': typeof TestdayRoute
  '/tests': typeof TestsRoute
  '/todos': typeof TodosRoute
  '/vehicle': typeof VehicleRoute
  '/waitinglist': typeof WaitinglistRoute
  '/waivers': typeof WaiversRoute
  '/weeklyreport': typeof WeeklyreportRoute
  '/courses/$id': typeof CoursesIdRoute
  '/courses/new': typeof CoursesNewRoute
  '/lessons/$id': typeof LessonsIdRoute
  '/lessons/new': typeof LessonsNewRoute
  '/messages/$id': typeof MessagesIdRoute
  '/notes/$id': typeof NotesIdRoute
  '/pupils/$id': typeof PupilsIdRoute
  '/pupils/new': typeof PupilsNewRoute
  '/quotes/new': typeof QuotesNewRoute
  '/courses/': typeof CoursesIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/pupils/': typeof PupilsIndexRoute
  '/quotes/': typeof QuotesIndexRoute
  '/lessons/edit/$id': typeof LessonsEditIdRoute
  '/lessons/feedback/$id': typeof LessonsFeedbackIdRoute
  '/lessons/reschedule/$id': typeof LessonsRescheduleIdRoute
  '/pupils/edit/$id': typeof PupilsEditIdRoute
  '/pupils/history/$id': typeof PupilsHistoryIdRoute
  '/pupils/progress/$id': typeof PupilsProgressIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automations'
    | '/availability'
    | '/briefing'
    | '/bulkmessage'
    | '/calendarsync'
    | '/certifications'
    | '/checklist'
    | '/cpd'
    | '/dataimport'
    | '/diary'
    | '/documents'
    | '/earnings'
    | '/enquiries'
    | '/eod'
    | '/expenses'
    | '/forgotpassword'
    | '/fuel'
    | '/gaps'
    | '/health'
    | '/help'
    | '/home'
    | '/livesession'
    | '/locations'
    | '/login'
    | '/manifest'
    | '/messages'
    | '/mileage'
    | '/monthend'
    | '/mtd'
    | '/notes'
    | '/notifications'
    | '/notificationsettings'
    | '/onboarding'
    | '/outstanding'
    | '/payments'
    | '/performance'
    | '/pipeline'
    | '/profile'
    | '/quickaccess'
    | '/quickavailability'
    | '/referrals'
    | '/register'
    | '/reminder'
    | '/reports'
    | '/resetpassword'
    | '/resources'
    | '/reviews'
    | '/rewards'
    | '/satnav'
    | '/schedule'
    | '/search'
    | '/settings'
    | '/standards'
    | '/subscription'
    | '/tax'
    | '/testday'
    | '/tests'
    | '/todos'
    | '/vehicle'
    | '/waitinglist'
    | '/waivers'
    | '/weeklyreport'
    | '/courses/$id'
    | '/courses/new'
    | '/lessons/$id'
    | '/lessons/new'
    | '/messages/$id'
    | '/notes/$id'
    | '/pupils/$id'
    | '/pupils/new'
    | '/quotes/new'
    | '/courses/'
    | '/notes/'
    | '/pupils/'
    | '/quotes/'
    | '/lessons/edit/$id'
    | '/lessons/feedback/$id'
    | '/lessons/reschedule/$id'
    | '/pupils/edit/$id'
    | '/pupils/history/$id'
    | '/pupils/progress/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automations'
    | '/availability'
    | '/briefing'
    | '/bulkmessage'
    | '/calendarsync'
    | '/certifications'
    | '/checklist'
    | '/cpd'
    | '/dataimport'
    | '/diary'
    | '/documents'
    | '/earnings'
    | '/enquiries'
    | '/eod'
    | '/expenses'
    | '/forgotpassword'
    | '/fuel'
    | '/gaps'
    | '/health'
    | '/help'
    | '/home'
    | '/livesession'
    | '/locations'
    | '/login'
    | '/manifest'
    | '/messages'
    | '/mileage'
    | '/monthend'
    | '/mtd'
    | '/notifications'
    | '/notificationsettings'
    | '/onboarding'
    | '/outstanding'
    | '/payments'
    | '/performance'
    | '/pipeline'
    | '/profile'
    | '/quickaccess'
    | '/quickavailability'
    | '/referrals'
    | '/register'
    | '/reminder'
    | '/reports'
    | '/resetpassword'
    | '/resources'
    | '/reviews'
    | '/rewards'
    | '/satnav'
    | '/schedule'
    | '/search'
    | '/settings'
    | '/standards'
    | '/subscription'
    | '/tax'
    | '/testday'
    | '/tests'
    | '/todos'
    | '/vehicle'
    | '/waitinglist'
    | '/waivers'
    | '/weeklyreport'
    | '/courses/$id'
    | '/courses/new'
    | '/lessons/$id'
    | '/lessons/new'
    | '/messages/$id'
    | '/notes/$id'
    | '/pupils/$id'
    | '/pupils/new'
    | '/quotes/new'
    | '/courses'
    | '/notes'
    | '/pupils'
    | '/quotes'
    | '/lessons/edit/$id'
    | '/lessons/feedback/$id'
    | '/lessons/reschedule/$id'
    | '/pupils/edit/$id'
    | '/pupils/history/$id'
    | '/pupils/progress/$id'
  id:
    | '__root__'
    | '/'
    | '/automations'
    | '/availability'
    | '/briefing'
    | '/bulkmessage'
    | '/calendarsync'
    | '/certifications'
    | '/checklist'
    | '/cpd'
    | '/dataimport'
    | '/diary'
    | '/documents'
    | '/earnings'
    | '/enquiries'
    | '/eod'
    | '/expenses'
    | '/forgotpassword'
    | '/fuel'
    | '/gaps'
    | '/health'
    | '/help'
    | '/home'
    | '/livesession'
    | '/locations'
    | '/login'
    | '/manifest'
    | '/messages'
    | '/mileage'
    | '/monthend'
    | '/mtd'
    | '/notes'
    | '/notifications'
    | '/notificationsettings'
    | '/onboarding'
    | '/outstanding'
    | '/payments'
    | '/performance'
    | '/pipeline'
    | '/profile'
    | '/quickaccess'
    | '/quickavailability'
    | '/referrals'
    | '/register'
    | '/reminder'
    | '/reports'
    | '/resetpassword'
    | '/resources'
    | '/reviews'
    | '/rewards'
    | '/satnav'
    | '/schedule'
    | '/search'
    | '/settings'
    | '/standards'
    | '/subscription'
    | '/tax'
    | '/testday'
    | '/tests'
    | '/todos'
    | '/vehicle'
    | '/waitinglist'
    | '/waivers'
    | '/weeklyreport'
    | '/courses/$id'
    | '/courses/new'
    | '/lessons/$id'
    | '/lessons/new'
    | '/messages/$id'
    | '/notes/$id'
    | '/pupils/$id'
    | '/pupils/new'
    | '/quotes/new'
    | '/courses/'
    | '/notes/'
    | '/pupils/'
    | '/quotes/'
    | '/lessons/edit/$id'
    | '/lessons/feedback/$id'
    | '/lessons/reschedule/$id'
    | '/pupils/edit/$id'
    | '/pupils/history/$id'
    | '/pupils/progress/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomationsRoute: typeof AutomationsRoute
  AvailabilityRoute: typeof AvailabilityRoute
  BriefingRoute: typeof BriefingRoute
  BulkmessageRoute: typeof BulkmessageRoute
  CalendarsyncRoute: typeof CalendarsyncRoute
  CertificationsRoute: typeof CertificationsRoute
  ChecklistRoute: typeof ChecklistRoute
  CpdRoute: typeof CpdRoute
  DataimportRoute: typeof DataimportRoute
  DiaryRoute: typeof DiaryRoute
  DocumentsRoute: typeof DocumentsRoute
  EarningsRoute: typeof EarningsRoute
  EnquiriesRoute: typeof EnquiriesRoute
  EodRoute: typeof EodRoute
  ExpensesRoute: typeof ExpensesRoute
  ForgotpasswordRoute: typeof ForgotpasswordRoute
  FuelRoute: typeof FuelRoute
  GapsRoute: typeof GapsRoute
  HealthRoute: typeof HealthRoute
  HelpRoute: typeof HelpRoute
  HomeRoute: typeof HomeRoute
  LivesessionRoute: typeof LivesessionRoute
  LocationsRoute: typeof LocationsRoute
  LoginRoute: typeof LoginRoute
  ManifestRoute: typeof ManifestRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  MileageRoute: typeof MileageRoute
  MonthendRoute: typeof MonthendRoute
  MtdRoute: typeof MtdRoute
  NotesRoute: typeof NotesRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  NotificationsettingsRoute: typeof NotificationsettingsRoute
  OnboardingRoute: typeof OnboardingRoute
  OutstandingRoute: typeof OutstandingRoute
  PaymentsRoute: typeof PaymentsRoute
  PerformanceRoute: typeof PerformanceRoute
  PipelineRoute: typeof PipelineRoute
  ProfileRoute: typeof ProfileRoute
  QuickaccessRoute: typeof QuickaccessRoute
  QuickavailabilityRoute: typeof QuickavailabilityRoute
  ReferralsRoute: typeof ReferralsRoute
  RegisterRoute: typeof RegisterRoute
  ReminderRoute: typeof ReminderRoute
  ReportsRoute: typeof ReportsRoute
  ResetpasswordRoute: typeof ResetpasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  ReviewsRoute: typeof ReviewsRoute
  RewardsRoute: typeof RewardsRoute
  SatnavRoute: typeof SatnavRoute
  ScheduleRoute: typeof ScheduleRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  StandardsRoute: typeof StandardsRoute
  SubscriptionRoute: typeof SubscriptionRoute
  TaxRoute: typeof TaxRoute
  TestdayRoute: typeof TestdayRoute
  TestsRoute: typeof TestsRoute
  TodosRoute: typeof TodosRoute
  VehicleRoute: typeof VehicleRoute
  WaitinglistRoute: typeof WaitinglistRoute
  WaiversRoute: typeof WaiversRoute
  WeeklyreportRoute: typeof WeeklyreportRoute
  CoursesIdRoute: typeof CoursesIdRoute
  CoursesNewRoute: typeof CoursesNewRoute
  LessonsIdRoute: typeof LessonsIdRoute
  LessonsNewRoute: typeof LessonsNewRoute
  PupilsIdRoute: typeof PupilsIdRoute
  PupilsNewRoute: typeof PupilsNewRoute
  QuotesNewRoute: typeof QuotesNewRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  PupilsIndexRoute: typeof PupilsIndexRoute
  QuotesIndexRoute: typeof QuotesIndexRoute
  LessonsEditIdRoute: typeof LessonsEditIdRoute
  LessonsFeedbackIdRoute: typeof LessonsFeedbackIdRoute
  LessonsRescheduleIdRoute: typeof LessonsRescheduleIdRoute
  PupilsEditIdRoute: typeof PupilsEditIdRoute
  PupilsHistoryIdRoute: typeof PupilsHistoryIdRoute
  PupilsProgressIdRoute: typeof PupilsProgressIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weeklyreport': {
      id: '/weeklyreport'
      path: '/weeklyreport'
      fullPath: '/weeklyreport'
      preLoaderRoute: typeof WeeklyreportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waivers': {
      id: '/waivers'
      path: '/waivers'
      fullPath: '/waivers'
      preLoaderRoute: typeof WaiversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitinglist': {
      id: '/waitinglist'
      path: '/waitinglist'
      fullPath: '/waitinglist'
      preLoaderRoute: typeof WaitinglistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle': {
      id: '/vehicle'
      path: '/vehicle'
      fullPath: '/vehicle'
      preLoaderRoute: typeof VehicleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testday': {
      id: '/testday'
      path: '/testday'
      fullPath: '/testday'
      preLoaderRoute: typeof TestdayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax': {
      id: '/tax'
      path: '/tax'
      fullPath: '/tax'
      preLoaderRoute: typeof TaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards': {
      id: '/standards'
      path: '/standards'
      fullPath: '/standards'
      preLoaderRoute: typeof StandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/satnav': {
      id: '/satnav'
      path: '/satnav'
      fullPath: '/satnav'
      preLoaderRoute: typeof SatnavRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resetpassword': {
      id: '/resetpassword'
      path: '/resetpassword'
      fullPath: '/resetpassword'
      preLoaderRoute: typeof ResetpasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminder': {
      id: '/reminder'
      path: '/reminder'
      fullPath: '/reminder'
      preLoaderRoute: typeof ReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quickavailability': {
      id: '/quickavailability'
      path: '/quickavailability'
      fullPath: '/quickavailability'
      preLoaderRoute: typeof QuickavailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quickaccess': {
      id: '/quickaccess'
      path: '/quickaccess'
      fullPath: '/quickaccess'
      preLoaderRoute: typeof QuickaccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outstanding': {
      id: '/outstanding'
      path: '/outstanding'
      fullPath: '/outstanding'
      preLoaderRoute: typeof OutstandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificationsettings': {
      id: '/notificationsettings'
      path: '/notificationsettings'
      fullPath: '/notificationsettings'
      preLoaderRoute: typeof NotificationsettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mtd': {
      id: '/mtd'
      path: '/mtd'
      fullPath: '/mtd'
      preLoaderRoute: typeof MtdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monthend': {
      id: '/monthend'
      path: '/monthend'
      fullPath: '/monthend'
      preLoaderRoute: typeof MonthendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mileage': {
      id: '/mileage'
      path: '/mileage'
      fullPath: '/mileage'
      preLoaderRoute: typeof MileageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest': {
      id: '/manifest'
      path: '/manifest'
      fullPath: '/manifest'
      preLoaderRoute: typeof ManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livesession': {
      id: '/livesession'
      path: '/livesession'
      fullPath: '/livesession'
      preLoaderRoute: typeof LivesessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaps': {
      id: '/gaps'
      path: '/gaps'
      fullPath: '/gaps'
      preLoaderRoute: typeof GapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fuel': {
      id: '/fuel'
      path: '/fuel'
      fullPath: '/fuel'
      preLoaderRoute: typeof FuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgotpassword': {
      id: '/forgotpassword'
      path: '/forgotpassword'
      fullPath: '/forgotpassword'
      preLoaderRoute: typeof ForgotpasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eod': {
      id: '/eod'
      path: '/eod'
      fullPath: '/eod'
      preLoaderRoute: typeof EodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiries': {
      id: '/enquiries'
      path: '/enquiries'
      fullPath: '/enquiries'
      preLoaderRoute: typeof EnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diary': {
      id: '/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof DiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dataimport': {
      id: '/dataimport'
      path: '/dataimport'
      fullPath: '/dataimport'
      preLoaderRoute: typeof DataimportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpd': {
      id: '/cpd'
      path: '/cpd'
      fullPath: '/cpd'
      preLoaderRoute: typeof CpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendarsync': {
      id: '/calendarsync'
      path: '/calendarsync'
      fullPath: '/calendarsync'
      preLoaderRoute: typeof CalendarsyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulkmessage': {
      id: '/bulkmessage'
      path: '/bulkmessage'
      fullPath: '/bulkmessage'
      preLoaderRoute: typeof BulkmessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing': {
      id: '/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof BriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes/': {
      id: '/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof QuotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pupils/': {
      id: '/pupils/'
      path: '/pupils'
      fullPath: '/pupils/'
      preLoaderRoute: typeof PupilsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof NotesRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes/new': {
      id: '/quotes/new'
      path: '/quotes/new'
      fullPath: '/quotes/new'
      preLoaderRoute: typeof QuotesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pupils/new': {
      id: '/pupils/new'
      path: '/pupils/new'
      fullPath: '/pupils/new'
      preLoaderRoute: typeof PupilsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pupils/$id': {
      id: '/pupils/$id'
      path: '/pupils/$id'
      fullPath: '/pupils/$id'
      preLoaderRoute: typeof PupilsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$id': {
      id: '/notes/$id'
      path: '/$id'
      fullPath: '/notes/$id'
      preLoaderRoute: typeof NotesIdRouteImport
      parentRoute: typeof NotesRoute
    }
    '/messages/$id': {
      id: '/messages/$id'
      path: '/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof MessagesIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/lessons/new': {
      id: '/lessons/new'
      path: '/lessons/new'
      fullPath: '/lessons/new'
      preLoaderRoute: typeof LessonsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$id': {
      id: '/lessons/$id'
      path: '/lessons/$id'
      fullPath: '/lessons/$id'
      preLoaderRoute: typeof LessonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/new': {
      id: '/courses/new'
      path: '/courses/new'
      fullPath: '/courses/new'
      preLoaderRoute: typeof CoursesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$id': {
      id: '/courses/$id'
      path: '/courses/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof CoursesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pupils/progress/$id': {
      id: '/pupils/progress/$id'
      path: '/pupils/progress/$id'
      fullPath: '/pupils/progress/$id'
      preLoaderRoute: typeof PupilsProgressIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pupils/history/$id': {
      id: '/pupils/history/$id'
      path: '/pupils/history/$id'
      fullPath: '/pupils/history/$id'
      preLoaderRoute: typeof PupilsHistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pupils/edit/$id': {
      id: '/pupils/edit/$id'
      path: '/pupils/edit/$id'
      fullPath: '/pupils/edit/$id'
      preLoaderRoute: typeof PupilsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/reschedule/$id': {
      id: '/lessons/reschedule/$id'
      path: '/lessons/reschedule/$id'
      fullPath: '/lessons/reschedule/$id'
      preLoaderRoute: typeof LessonsRescheduleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/feedback/$id': {
      id: '/lessons/feedback/$id'
      path: '/lessons/feedback/$id'
      fullPath: '/lessons/feedback/$id'
      preLoaderRoute: typeof LessonsFeedbackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/edit/$id': {
      id: '/lessons/edit/$id'
      path: '/lessons/edit/$id'
      fullPath: '/lessons/edit/$id'
      preLoaderRoute: typeof LessonsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MessagesRouteChildren {
  MessagesIdRoute: typeof MessagesIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesIdRoute: MessagesIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

interface NotesRouteChildren {
  NotesIdRoute: typeof NotesIdRoute
  NotesIndexRoute: typeof NotesIndexRoute
}

const NotesRouteChildren: NotesRouteChildren = {
  NotesIdRoute: NotesIdRoute,
  NotesIndexRoute: NotesIndexRoute,
}

const NotesRouteWithChildren = NotesRoute._addFileChildren(NotesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomationsRoute: AutomationsRoute,
  AvailabilityRoute: AvailabilityRoute,
  BriefingRoute: BriefingRoute,
  BulkmessageRoute: BulkmessageRoute,
  CalendarsyncRoute: CalendarsyncRoute,
  CertificationsRoute: CertificationsRoute,
  ChecklistRoute: ChecklistRoute,
  CpdRoute: CpdRoute,
  DataimportRoute: DataimportRoute,
  DiaryRoute: DiaryRoute,
  DocumentsRoute: DocumentsRoute,
  EarningsRoute: EarningsRoute,
  EnquiriesRoute: EnquiriesRoute,
  EodRoute: EodRoute,
  ExpensesRoute: ExpensesRoute,
  ForgotpasswordRoute: ForgotpasswordRoute,
  FuelRoute: FuelRoute,
  GapsRoute: GapsRoute,
  HealthRoute: HealthRoute,
  HelpRoute: HelpRoute,
  HomeRoute: HomeRoute,
  LivesessionRoute: LivesessionRoute,
  LocationsRoute: LocationsRoute,
  LoginRoute: LoginRoute,
  ManifestRoute: ManifestRoute,
  MessagesRoute: MessagesRouteWithChildren,
  MileageRoute: MileageRoute,
  MonthendRoute: MonthendRoute,
  MtdRoute: MtdRoute,
  NotesRoute: NotesRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  NotificationsettingsRoute: NotificationsettingsRoute,
  OnboardingRoute: OnboardingRoute,
  OutstandingRoute: OutstandingRoute,
  PaymentsRoute: PaymentsRoute,
  PerformanceRoute: PerformanceRoute,
  PipelineRoute: PipelineRoute,
  ProfileRoute: ProfileRoute,
  QuickaccessRoute: QuickaccessRoute,
  QuickavailabilityRoute: QuickavailabilityRoute,
  ReferralsRoute: ReferralsRoute,
  RegisterRoute: RegisterRoute,
  ReminderRoute: ReminderRoute,
  ReportsRoute: ReportsRoute,
  ResetpasswordRoute: ResetpasswordRoute,
  ResourcesRoute: ResourcesRoute,
  ReviewsRoute: ReviewsRoute,
  RewardsRoute: RewardsRoute,
  SatnavRoute: SatnavRoute,
  ScheduleRoute: ScheduleRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  StandardsRoute: StandardsRoute,
  SubscriptionRoute: SubscriptionRoute,
  TaxRoute: TaxRoute,
  TestdayRoute: TestdayRoute,
  TestsRoute: TestsRoute,
  TodosRoute: TodosRoute,
  VehicleRoute: VehicleRoute,
  WaitinglistRoute: WaitinglistRoute,
  WaiversRoute: WaiversRoute,
  WeeklyreportRoute: WeeklyreportRoute,
  CoursesIdRoute: CoursesIdRoute,
  CoursesNewRoute: CoursesNewRoute,
  LessonsIdRoute: LessonsIdRoute,
  LessonsNewRoute: LessonsNewRoute,
  PupilsIdRoute: PupilsIdRoute,
  PupilsNewRoute: PupilsNewRoute,
  QuotesNewRoute: QuotesNewRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  PupilsIndexRoute: PupilsIndexRoute,
  QuotesIndexRoute: QuotesIndexRoute,
  LessonsEditIdRoute: LessonsEditIdRoute,
  LessonsFeedbackIdRoute: LessonsFeedbackIdRoute,
  LessonsRescheduleIdRoute: LessonsRescheduleIdRoute,
  PupilsEditIdRoute: PupilsEditIdRoute,
  PupilsHistoryIdRoute: PupilsHistoryIdRoute,
  PupilsProgressIdRoute: PupilsProgressIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
